spring:
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_NAME:jfundCandles}
      password: ${DB_PASSWORD:float123}
      username: ${DB_USER:jfund}
      authentication-database: admin

app:
  currencyApi:
    accessKey: ${CURRENCY_ACCESS_KEY:c2d601fea1abdae7dab05755852cd1d1}

  kafka:
    server: ${KAFKA_SERVER:localhost:9092}
    currency-values-topic: ${CURRENCY_VALUES_TOPIC:jfund-currency-values}